apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd

spec:
  description: Allow access to my GitOps repository

  sourceRepos:
    - https://github.com/sbaransi/gitops.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  sourceNamespaces:
    - '*'
